-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXyUFGt7MJ9mr2Myd
reAvfkpzjoTbtndNAxtcS4fB+vmgCgYIKoZIzj0DAQehRANCAATJuFNeI7Cd4PUi
S3HUBthGVNs6wdVlyaQuSpSWJTxi8y9ahlck8uLTIhSiECJSEKOMQ+H7Vssw07HQ
0vQa88Lx
-----END PRIVATE KEY-----