-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQga6DkYYvwCSbQIaWw
TIocCAdBGXRMo1WuXmvYOQFBA/GgCgYIKoZIzj0DAQehRANCAATv/1MzeYQ6kgZi
Jf6cVNZtx0ZimsABKjRQK61lL/YAFdP1NzuKnDtis9dmZzOS7GtwyO+jwvmYrSUP
ZmGqvkNz
-----END PRIVATE KEY-----